spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/test2
    username: postgres
    password: 1234
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none